feat: support react-aria-components render prop
gregberge/twc pull request #20
Opened 2023-12-23 17:48 UTC by gregberge

Fix #11

2023-12-23 23:18 UTC, izznatsir requested changes

2023-12-23 23:18 UTC, izznatsir commented on src/index.test.tsx
> +            )
`_prev` should be composed with the return value of `fp(renderProps`. Wrap it with `twMerge` or `clsx` will suffice.

```javascript
...
        ? composeRenderProps(className, (prevClassName, renderProps) =>
                twMerge(prevClassName, fn(renderProps)),
            )
...
```

2023-12-23 23:20 UTC, izznatsir commented
This approach is brilliant!

2023-12-24 10:12 UTC, gregberge commented
@devongovett could you please give a review on this? What do you think?

https://twc-o3f01nfwe-argos-ci.vercel.app/docs/integrations/react-aria-components

2023-12-24 10:14 UTC, gregberge commented
@izznatsir final implementation, please review :)

2023-12-24 12:38 UTC, gregberge commented
I finally find a way to support it without any adapter 🎉

2023-12-24 12:42 UTC, merged

2023-12-24 18:14 UTC, ducan-ne commented
@gregberge Do you think this API could be way better?
```js
const Button = twc(AriaButton)<ButtonProps>(
  (props, { isPressed }) => =>
    isPressed ? "bg-gray-700" : "bg-gray-500",
);
```
I'm uncertain about the technical aspect.